a <- readline('Enter the first number : ')
b <- readline('Enter the second number : ')
a <- as.integer(a)
b <- as.integer(b)
#print(paste('Sum : a+b=',a+b))
#print(paste('Diffrence : a-b=',a-b))
#print(paste('Product : a*b=',a*b))
#print(paste('Divisor : a/b=',a/b))
cat('Sum : a+b=',a+b,'\n')
cat('Diffrence : a-b=',a-b,'\n')
cat('Product : a*b=',a*b,'\n')
cat('Divisor : a/b=',a/b,'\n')